### ISSUE TITLE
mo-pack needs some love...

### ISSUE THREAD

**Issue by bjlittle** [SciTools/mo_pack#13]
Well, where to start...

`mo-pack` does need a wee bit of love to breath some life back into it e.g.,

- `master` to `main`
- adopt GHA for CI i.e., drop `travis-ci`
- building and testing of PyPI `sdist` and binary `wheels`
- min pin for a modern version of python e.g., `py>=3.8`

**Comment by jfrost-mo** [comment]
This was fixed with #16.
