### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by jfrost-mo** [SciTools/mo_pack#15]
mo_pack is the only package in my dependency tree that doesn't support python 3.12 yet. It would be great to have support :)

**Comment by jfrost-mo** [comment]
It might actually work already, in which case it is just the conda-forge recipe that needs updating.

**Comment by jfrost-mo** [comment]
See https://github.com/conda-forge/mo_pack-feedstock/pull/32 for my work on getting this updated.

**Comment by bjlittle** [comment]
@jfrost-mo `mo_pack` needs a whole lot of infra-structure maintenance and :heart: ... spinning up on that now to breath some life back into it :+1:

**Comment by jfrost-mo** [comment]
Thanks Bill ❤️

**Comment by bjlittle** [comment]
The `conda-forge` bot has built `mo_pack` 0.3.0 for `py312`, so your now unblocked 👍

**Comment by jfrost-mo** [comment]
In testing I can now install mo_pack in a python 3.12 environment. :tada:
